alias tkill="tmux kill-server" 
alias memo="rusmo"
alias g="git"
alias ls="exa -a "
alias ll="exa -alFh --git --time-style=long-iso"; 
alias cat="bat"
alias mkdir="mkdir -p"
alias dc="docker-compose" 
alias cp="cp -r"
alias d="docker"
alias v="vim"
alias alldel="bash ~/dotfiles/docker/all_down.sh"
alias fdown="docker-compose down --rmi all --volumes --remove-orphans"
alias recon="source ~/.${SHELL##*/}rc"
alias shconf="$EDITOR ~/.${SHELL##*/}rc"
#change dir
alias cdw="cd ~/workspace/"
alias cdv="cd ~/vagrant/"
alias cdd="cd ~/dotfiles/"
alias zi="zoxied"
alias diff="vimdiff"

#about tmux
if [[ ! -n $TMUX && $- == *l* ]]; then
  # get the IDs
  ID="`tmux list-sessions`"
  if [[ -z "$ID" ]]; then
    tmux new-session
  fi
  create_new_session="Create New Session"
  ID="$ID\n${create_new_session}:"
  ID="`echo $ID | peco | cut -d: -f1`"
  if [[ "$ID" = "${create_new_session}" ]]; then
    tmux new-session
  elif [[ -n "$ID" ]]; then
    tmux attach-session -t "$ID"
  else
    :  # Start terminal normally
  fi
fi

#path
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export EDITOR=vim
export PATH=~/.npm-global/bin:$PATH
export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
export PATH="/usr/local/opt/binutils/bin:$PATH"

eval "$(zoxide init zsh)"
# eval "$(starship init zsh)"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source /home/hasu/Downloads/alacritty/extra/completions/alacritty.bash

# $ git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
plugins=(zsh-autosuggestions)
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh


function do_ls(){

  if [[ -n "$BUFFER" ]]; then
    zle accept-line
    return 0
  fi

  #if current dir is git repo, show now branch
  if git rev-parse --git-dir > /dev/null 2>&1; then
    echo "\n[branch]"
    echo "$(git rev-parse --abbrev-ref @)"
  fi

   ls
   echo "\n"

  zle reset-prompt
  return 0
}

zle -N do_ls
bindkey '^m' do_ls

autoload -Uz colors && colors
if [ -n "$SSH_CLIENT" ]; then
	isssh="${RED}[ssh]${RESET}"
else
	isssh="${GREEN}[local]${RESET}"
fi

PS1="%F{cyan}%D{%Y-%m-%d}${reset_color%} %F{cyan}$vcs_info_msg_0_%f%F{yellow}%f
${isssh} %n@%m: %F{cyan}%~ ${reset_color%} 
\$ "
# PS1="$ "
