alias tkill="tmux kill-server"
alias memo="rusmo"
alias g="git"
alias lg="lazygit"
alias ls="exa -a"
alias ll="exa -alFh --git --time-style=long-iso";
alias cat="bat"
alias mkdir="mkdir -p"
alias dc="docker-compose"
alias cp="cp -r"
alias d="docker"
alias alldel="bash ~/dotfiles/docker/all_down.sh"
alias fdown="docker-compose down --rmi all --volumes --remove-orphans"
alias recon="source ~/.${SHELL##*/}rc"
alias shconf="$EDITOR ~/.${SHELL##*/}rc"
alias vim="nvim"
alias zi="zoxide"
alias cls="clear"
alias diff="vimdiff"
#change dir
alias cdw="cd ~/workspace/"
alias cdv="cd ~/vagrant/"
alias cdd="cd ~/dotfiles/"

#about tmux
if [[ ! -n $TMUX && $- == *l* ]]; then
  # get the IDs
  ID="`tmux list-sessions`"
  if [[ -z "$ID" ]]; then
    tmux new-session
  fi
  create_new_session="Create New Session"
  ID="$ID\n${create_new_session}:"
  ID="`echo $ID | peco | cut -d: -f1`"
  if [[ "$ID" = "${create_new_session}" ]]; then
    tmux new-session
  elif [[ -n "$ID" ]]; then
    tmux attach-session -t "$ID"
  else
    :  # Start terminal normally
  fi
fi

#path
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export EDITOR=vim
export PATH=~/.npm-global/bin:$PATH export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
export PATH=/usr/local/opt/binutils/bin:$PATH
export PATH=$PATH:/usr/local/go/bin
export PATH=/usr/local/opt/llvm@9/bin:$PATH
export PATH=/usr/local/opt/dosfstools/sbin:$PATH

eval "$(zoxide init zsh)"
eval "$(gh completion -s zsh)"
#eval "$(starship init zsh)"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# $ git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
plugins=(zsh-autosuggestions)
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

function select-history() {
  BUFFER=$(history -n -r 1 | fzf --no-sort +m --query "$LBUFFER" --prompt=">> ")
  CURSOR=$#BUFFER
}
zle -N select-history
bindkey '^r' select-history


autoload -Uz colors && colors
if [ -n "$SSH_CLIENT" ]; then
	isssh="%F{red}[ssh]${reset_color%}"
else
	isssh="%F{green}[local]${reset_color%}"
fi

PS1="${isssh} %n@%m: %F{cyan}%~ ${reset_color%} 
\$ "
# PS1="$ "
