"vim 初回起動時vim-plug自動インストール{{{
    set rtp+=~/.vim/plugged/vim-plug
    " install vim-pulg
    if has('vim_starting')
            if !isdirectory(expand('~/.vim/plugged/'))
              echo 'install vim-plug...'
              call mkdir('~/.vim/plugged')
              call system('curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim')
            endif
    endif
" }}}

exec 'source' expand('~/dotfiles/vim/plugin.vim')
exec 'source' expand('~/dotfiles/vim/editor.vim')
exec 'source' expand('~/dotfiles/vim/keymap.vim')
exec 'source' expand('~/dotfiles/vim/denite.vim')

