
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
#export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.cargo/env:$PATH"
export EDITOR=vim
export PATH=~/.npm-global/bin:$PATH export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
export PATH=/usr/local/opt/binutils/bin:$PATH
export PATH=$PATH:/usr/local/go/bin
export PATH=/usr/local/opt/llvm@9/bin:$PATH
export PATH=/usr/local/opt/dosfstools/sbin:$PATH
export PATH="/usr/local/opt/bison/bin:$PATH"
if [ -d $HOME/.zsh/comp ]; then
    export FPATH="$HOME/.zsh/comp:$FPATH"
fi
export PATH=$PATH:/usr/local/go/bin
export GOPATH=~/dev/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
