
if [ "$(uname)" = "Darwin" ]; then
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
fi

export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libtiff/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/gmp/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libpng/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/ncurses/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/mpfr/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libyaml/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/icu4c/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/readline4/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/webp/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/unixodbc/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/jpeg/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libpq/lib/pkgconfig"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export EDITOR=vim
export PATH=~/.npm-global/bin:$PATH export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
export PATH=/usr/local/opt/binutils/bin:$PATH
export PATH=$PATH:/usr/local/go/bin
export PATH=/usr/local/opt/llvm@9/bin:$PATH
export PATH=/usr/local/opt/dosfstools/sbin:$PATH
export PATH="/usr/local/opt/bison/bin:$PATH"
if [ -d $HOME/.zsh/comp ]; then
    export FPATH="$HOME/.zsh/comp:$FPATH"
fi
export PATH=/usr/local/bin/git:/usr/local/opt/bison/bin:/usr/local/opt/dosfstools/sbin:/usr/local/opt/llvm@9/bin:/usr/local/opt/binutils/bin:/home/hasu/.deno/bin:/home/hasu/.npm-global/bin:/home/hasu/.cargo/bin:/home/hasu/.yarn/bin:/home/hasu/.config/yarn/global/node_modules/.bin:/usr/local/opt/bison/bin:/usr/local/opt/dosfstools/sbin:/usr/local/opt/llvm@9/bin:/usr/local/opt/binutils/bin:/home/hasu/.deno/bin:/home/hasu/.npm-global/bin:/home/hasu/.cargo/bin:/home/hasu/.yarn/bin:/home/hasu/.config/yarn/global/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin
export PATH=$PATH:/usr/local/go/bin
export GOPATH=~/dev/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN

EDITOR="nvim"
. "$HOME/.cargo/env"
if [ -e /Users/hasu/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/hasu/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
