#alias
alias tkill="tmux kill-server"
alias memo="rusmo"
alias g="git"
alias lg="lazygit"
alias ls="exa -a"
alias ll="exa -alFh --git --time-style=long-iso";
alias cat="bat"
alias mkdir="mkdir -p"
alias d="docker"
alias dc="docker-compose"
alias ds="sh $HOME/dotfiles/shell/docker.sh"
alias cp="cp -r"
alias alldel="bash ~/dotfiles/docker/all_down.sh"
alias fdown="docker-compose down --rmi all --volumes --remove-orphans"
alias recon="source ~/.${SHELL##*/}rc"
alias shconf="$EDITOR ~/.${SHELL##*/}rc"
alias vim="nvim"
alias zi="zoxide"
alias cls="clear"
alias diff="vimdiff"
alias ys="yay -S"
#change dir
alias cdw="cd ~/workspace/"
alias cdv="cd ~/vagrant/"
alias cdd="cd ~/dotfiles/"

EDITOR="nvim"

eval "$(zoxide init zsh)"
eval "$(gh completion -s zsh)"
eval "$(starship init zsh)"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
# plugins=(zsh-autosuggestions)
# source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
fpath=(~/.zsh/completion $fpath)
autoload -U compinit
compinit -u

function select-history() {
  BUFFER=$(history -n -r 1 | fzf --no-sort +m --query "$LBUFFER" --prompt=">> ")
  CURSOR=$#BUFFER
}

zle -N select-history
bindkey '^r' select-history

# 履歴ファイルの保存先
export HISTFILE=${HOME}/.zsh_history

# メモリに保存される履歴の件数
export HISTSIZE=100

# 履歴ファイルに保存される履歴の件数
export SAVEHIST=10000

# norecord duplicate command
setopt hist_ignore_dups

#no record history command
setopt hist_no_store

setopt hist_save_no_dups

setopt auto_cd
cdpath=(.. ~ ~/workspace)

setopt correct

#do not create .lesshist
export LESSHISTFILE=-
